db:
  driver:
    class:
      name: org.hsqldb.jdbcDriver
  url: jdbc:hsqldb:mem:db

server:
  port: 5000

cake:
  url: 'https://gist.githubusercontent.com/hart88/198f29ec5114a3ec3460/raw/8dd19a88f9b8d24c23d9960f3300d0c917a4f07c/cake.json'